# Generated by Django 4.2.28 on 2026-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
