# Generated by Django 5.2.1 on 2026-02-27 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
